### ISSUE TITLE
베타테스터 미엘이 써보고 이슈 드립니다.

### ISSUE THREAD

**Issue by ynifamily3** [Phryxia/tagmemo#1]
버그

- [x] - 같은 태그 여러 개 지정 후 그 중 하나를 삭제하면 모두 삭제되는 현상
- [x] - 의도한건진 모르겠는데, 같은 태그 여러 번 입력할 수 있는 현상
- [x] - 태그가 많으면 스타일이 깨짐 

개선점

- [x] - 메모 생성 버튼 클릭 시 바로 메모가 생성됨 (의도한건지 모르겠으나, 의도했다면 취소를 누를 때 메모가 도로 삭제되었으면 좋을 것 같습니다.)
- [x] - '내용을 입력하세요...' 부분을 기본값으로 하는 대신에 placeholder로 하시는 게 좋을 것 같습니다.
- [x] - '확인' '취소' 버튼 순서를 반대로 하시는 게 어떤가요?
- [x] - 모달에서 ESC를 누르거나 외부 영역을 클릭하면 창이 사라지는 게 좋을 듯 (수정 중일 경우 confirm 한 번 띄워주면 좋을 듯)
_- [ ] - 메모 입력 도중 ctrl(command) + enter 누르면 바로 확인 누른 효과 나도록 하는 게 좋을 것 같습니다._ -> 취소

**Comment by Phryxia** [comment]
* 메모 생성 버튼 클릭 시 바로 메모가 생성됨 (의도한건지 모르겠으나, 의도했다면 취소를 누를 때 메모가 도로 삭제되었으면 좋을 것 같습니다.)

이건 솔직히 로직 단순화하려고 짠거라 수정하기 귀찮아여... 예정은 해둘게

* 모달에서 ESC를 누르거나 외부 영역을 클릭하면 창이 사라지는 게 좋을 듯 (수정 중일 경우 confirm 한 번 띄워주면 좋을 듯)

외부 영역 클릭 시 취소 안되는건 일부로 의도한 거임. 특히 모바일 환경에서 실수로 바깥 터치했는데 작성한 거 날아가면 화남 (다른 사이트에서 많이 겪어봄) 그래서 취소 버튼을 명시적으로 달아놓은 것.

키보드 대응은 예정은 해둘게

결론: 아 일하기 싫다

**Comment by ynifamily3** [comment]
[제보] 태그 쓰다가 포커스 잃어버리면 쓰다가 만 태그는 자동으로 추가해 주면 좋을 것 같습니다.

**Comment by ynifamily3** [comment]
[제보] 태그가 이미 있을 때, 새 태그 추가 시 아무것도 없으면 백스페이스를 눌렀을 때 기존에 추가된 태그가 하나씩 지워졌으면 좋을 듯(?)

**Comment by Phryxia** [comment]
@ynifamily3  
[제보] 태그가 이미 있을 때, 새 태그 추가 시 아무것도 없으면 백스페이스를 눌렀을 때 기존에 추가된 태그가 하나씩 지워졌으면 좋을 듯(?)

이거 체크 돼 있는데 지금 작업 중인 PR에 반영하고 계신가염

**Comment by ynifamily3** [comment]
코드 수정 중... (포크해서)

**Comment by ynifamily3** [comment]
- [x] 수정되거나 추가된 내용이 없을 때에는 확인을 눌러도 반응하지 않도록 수정

**Comment by Phryxia** [comment]
@ynifamily3 수정되거나 추가된 내용이 없을 때에는 확인을 눌러도 반응하지 않도록 수정

UX에 별로 안좋을 거 같은데 이건 하지 말지
확인을 누르면 아무튼 창이 닫히기를 기대할텐데
