### ISSUE TITLE
tagsArrayAreEqual Review

### ISSUE THREAD

**Issue by KwonTF** [Phryxia/tagmemo#2]
https://github.com/Phryxia/tagmemo/blob/6f653f0b796fe712301f7a449ccb6d2737c2741b/src/Memo.ts#L19
out을 즉시 리턴하지 않고 let으로 두고 한번 사용하는 이유?

https://github.com/Phryxia/tagmemo/blob/6f653f0b796fe712301f7a449ccb6d2737c2741b/src/Memo.ts#L29
`[1,3,2] [1,4,2]`
상황은 같은 배열로 취급할거 같은데 문제되지 않는지

**Comment by Phryxia** [comment]
첫 번째 건 좋은 지적인듯

두 번째 지적은 틀렸음
일단 정렬을 하면 [1, 2, 3], [1, 2, 4]가 될거고
`i`가 `2`이면 `arr1[i] === 3`, `arr2[i] === 4`가 되어 `out`이 `false`가 됨

**Comment by KwonTF** [comment]
정렬이 돌아가서 같은 구조를 가지게 되네요
