### ISSUE TITLE
Simple Review

### ISSUE THREAD

**Issue by KwonTF** [Phryxia/tagmemo#3]
https://github.com/Phryxia/tagmemo/blob/6f653f0b796fe712301f7a449ccb6d2737c2741b/src/SearchedMemoList.tsx#L19

`React.Fragment => <>` 로 처리 가능한지

https://github.com/Phryxia/tagmemo/blob/6f653f0b796fe712301f7a449ccb6d2737c2741b/src/MemoEditor.tsx#L23

구조분해 할당후 초깃값 선언 가능한지

**Comment by Phryxia** [comment]
2번 무슨 말인지 모르겠어요 우마무스메

**Comment by KwonTF** [comment]
`const {content, tags, modifiedAt} = memo `

**Comment by Phryxia** [comment]
MemoEditor의 state로 content, tags, modifiedAt가 있는건데 저렇게 대입하면 안되쥬

**Comment by KwonTF** [comment]
변수명으로 각자 선언되어 있는걸 못봣네여ㅛ
